### ISSUE TITLE
PyMVVM cant resolve

### ISSUE THREAD

**Issue by bradws** [fridayowl/PyMVVM#1]
Hey :)

What's your pip installation command?

I did a `pip install pyMVVM` in my conda environment after installing Python
and it seemed to install ok, but my main.py file can't resolve the `from PyMVVM ...` line in your [gui_example.py](https://github.com/fridayowl/PyMVVM/blob/main/examples/gui_example.py) code example.

![image](https://github.com/user-attachments/assets/8ce709ee-9631-4ef2-a35e-5e5cdd4430a0)

**Comment by fridayowl** [comment]
Hey .
Can you confirm whether you have piped this  libe
https://pypi.org/project/pymvvm-design/

**Comment by bradws** [comment]
Yes, thank-you i can install it correctly now with 

`pip install pymvvm-design`

Also, I would be happy to contribute to the documentation if you like, however I don't seem to be able to have the correct access rights to be able to push to main Branch, and I wasn't able to create a Pull Request.
