### ISSUE TITLE
gui_example.py view 'count' not updating

### ISSUE THREAD

**Issue by bradws** [fridayowl/PyMVVM#2]
Hi,

I can [get basic_usage.py](https://github.com/fridayowl/PyMVVM/blob/main/examples/basic_usage.py) and [advanced_usage.py](https://github.com/fridayowl/PyMVVM/blob/main/examples/advanced_usage.py) working, but with [gui_example.py](https://github.com/fridayowl/PyMVVM/blob/main/examples/gui_example.py): the tkinter window appears, but the _increment_ and _decrement_ buttons have no effect on the count variable in the window !?!

Clicking the _increment_ and _decrement_ buttons does in fact modify the _self.model.count_ variable, but i think the view's _update(self)_ method isn't called. I notice that every View always seems to have an _update(self)_ method - maybe can you elaborate on when/how this _update(self)_ is called from the ViewModel so I can get a better understanding?

**Comment by fridayowl** [comment]
Let me check on it.  Give me some  time  you can drop a message on my
what's number also "+91 9846560463"

**Comment by fridayowl** [comment]
Hey thanks for pointing it out,  i have made few changes on the example
file

- *Simplified Property Chain*:

   - Previous: Complex observer pattern with multiple layers
   - Now: Direct model update → explicit notification → forced view update

- *Removed Custom Observer Logic*:

   - Previous: Custom observer methods and property bindings
   - Now: Using PyMVVM's built-in notification system

- *Added Safety Mechanism*:

   - Previous: Relied solely on automatic updates
   - Now: Added safe_command to ensure updates happen

- *Proper Base Class Usage*:

   - Previous: Mixed custom and framework functionality
   - Now: Properly leveraging PyMVVM's base classes


Code after changes :
import tkinter as tk
from PyMVVM import create_mvvm, ViewModel, View, Command,
computed_property, bindable_property

class CounterViewModel(ViewModel):
    def __init__(self, model):
        super().__init__(model)
        self.increment_command = Command(self.increment)
        self.decrement_command = Command(self.decrement)

    @computed_property
    def count_text(self):
        return f"Count: {self.model.count}"

    def increment(self):
        current_count = self.model.count
        self.model.count = current_count + 1
        # Force notification
        self.notify_observers('count_text')

    def decrement(self):
        current_count = self.model.count
        self.model.count = current_count - 1
        # Force notification
        self.notify_observers('count_text')

class CounterView(View):
    def __init__(self, view_model):
        # First store view_model reference
        self.view_model = view_model
        # Then setup UI
        self.setup_ui()
        # Finally initialize base class
        super().__init__(view_model)

    def setup_ui(self):
        self.root = tk.Tk()
        self.root.title("Counter Example")

        self.frame = tk.Frame(self.root, padx=20, pady=20)
        self.frame.pack(expand=True)

        self.label = tk.Label(
            self.frame,
            text=self.view_model.count_text,
            font=('Helvetica', 16)
        )
        self.label.pack(pady=10)

        button_frame = tk.Frame(self.frame)
        button_frame.pack(pady=5)

        self.increment_button = tk.Button(
            button_frame,
            text="+",
            command=lambda:
self.safe_command(self.view_model.increment_command),
            width=5,
            font=('Helvetica', 12)
        )
        self.increment_button.pack(side=tk.LEFT, padx=5)

        self.decrement_button = tk.Button(
            button_frame,
            text="-",
            command=lambda:
self.safe_command(self.view_model.decrement_command),
            width=5,
            font=('Helvetica', 12)
        )
        self.decrement_button.pack(side=tk.LEFT, padx=5)

        self.root.minsize(200, 150)
        self.center_window()

    def safe_command(self, command):
        """Wrapper to ensure command execution triggers updates"""
        command()
        self.update()

    def update(self):
        """Update the view when properties change"""
        self.label.config(text=self.view_model.count_text)

    def center_window(self):
        self.root.update_idletasks()
        width = self.root.winfo_width()
        height = self.root.winfo_height()
        x = (self.root.winfo_screenwidth() // 2) - (width // 2)
        y = (self.root.winfo_screenheight() // 2) - (height // 2)
        self.root.geometry(f'{width}x{height}+{x}+{y}')

    def run(self):
        self.root.mainloop()

def main():
    # Create MVVM components using the framework's factory function
    model, vm, view = create_mvvm(
        model_attrs={'count': 0},  # Initial model attributes
        view_model_class=CounterViewModel,
        view_class=CounterView
    )
    view.run()

if __name__ == "__main__":
    main()
